version: '3'

services:
  backend:
    container_name: fast_api
    build: .
    volumes:
      - .:/app/backend

    command: ['uvicorn', 'main:app', '--reload', '--host', '0.0.0.0', '--port','8000']
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env

volumes:
  postgres_data: